# Site settings
title: 腾讯电脑管家企业版
email: aaa@trantect.com
description: > # About PBE.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4001" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
port: 4001

# Build settings
markdown: kramdown
